# Generated by Django 6.0 on 2026-01-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(help_text='Comma separated skills like Python, Django, ML')),
                ('freelancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
