# Generated by Django 6.0 on 2026-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
